---
title: Devel
runtime: shiny
output:
   flexdashboard::flex_dashboard:
      logo: https://wwf.ru/assets/img/logo.jpg
      favicon: https://d1diae5goewto1.cloudfront.net/_skins/favicon.png
      orientation: columns
      mathjax: ~
      theme: yeti
      css:
      - site_libs/common.css
      - site_libs/flex_dashboard.css
      navbar:
         - { title: "ArcNet", icon: "fa-info-circle", href: "https://arcticwwf.org/work/ocean/arcnet/", align: right, target: _blank}
---


```{css}
   .leaflet-container {
       background-color: #fff;
   }
   .info.legend{
       background-color: #EEEA;
   }
   .marker-icon,
   .marker-icon:focus {
     border: 1px solid #33ff88 !important;
   }
   .dataTables_info .form-control {
      height: 24px;
   }
   .dataTables_filter .form-control {
      height: 24px;
      margin-top: -1em;
   }
   #cfmeta {
      font-size: 150%;
   }
```
# Main {#main}

```{r}
fillCol(flex=c(NA,1)
       ,textOutput('cfmeta')
       ,DT::DTOutput('cfdata')
       )
```

```{r}
output$cfmeta <- renderText({
   "CF here"
})
```

```{r}
output$cfdata <- DT::renderDT({
   DT::datatable(iris,extension="Scroller"
                ,options=list(scrollY="calc(100vh - 205px)",dom="ift")
   )
})
```
