---
output: html_fragment
bibliography: C:/RAS/2024/ArcNet/geranium/industries/Activities_pl.bib
---
### FSE: Seine and Stationary Seine Fishing

This type of fishing poses relatively low risk for biodiversity. However, stationary seines can cause bycatch or entanglement of marine mammals (seals, beluga whales, and even bowhead whales).

*Examples:* This type of fishing method is used in the Atlantic and in the Pacific sectors of the Arctic -- in the Bering, Chukchi, White and Barents Seas. It is used to catch salmon, saffron cod, and herring. It is used in shallow, coastal areas and is often installed for the short season when anadromous fish are coming into the rivers.

#### Assessment findings:

*Marine mammals:* Source of *notable* concern for the majority of CFs where measures to prevent seal entanglement and pingers to keep away smaller cetaceans (like porpoises) should be implemented. Source of *significant* concern in critical habitats.

*Seabirds:* Source of *significant* or *notable* concern for most CFs and seabird colonies and known regular bird aggregation areas should be avoided.

*Fish:* Source of *minor* concern for the majority of CFs.

*Benthos:* Source of *minor* concern for benthic features where applicable.

*Coastal features:* source of *significant* concern for kelp CFs, and intertidal zones. Source of *notable* concern for estuaries where the activity can take place at a limited scale only.

#### Assumptions:

We assumed that seine and stationary seine fishing can only take place in the coastal waters not more than 45 km (1.5 planning unit) from shore and with depths less than 20 m during the ice-free seasons.

#### Data sources:

The dataset represents areas where stationary seine gear was used for fishing based on @RN23 by VNIRO (Russia).

*Dataset produced:* September 2023.

### References
