## Постановка проблемы / цель

По проекту WWF® ArcNet построена cеть приоритетных районов в Северном Ледовитом океане и сопредельных морях для сохранения биоразнообразия на основе комплексной оценки биологической ценности локальных экосистем, сгруппированных по принципу эффективного территориального управления. В качестве исходных данных использовались, преимущественно, пространственное распределение объектов живой природы и средообразующих факторов по результатам наблюдений и экспертных оценок.

Инструмент Geranium предназначен для отображения сочетаемости интересов развития хозяйственной деятельности и сохранения окружающей среды, которая ранжирована экспертами по трем категориям, отвечающим за полную совместимость (хозяйственная деятельность не оказывает влияние на проведение природоохранных мер), частичную совместимость (необходимость ограничения хозяйственной деятельности) и несовместимость (отрицательное влияние хозяйственной деятельности при выполнении мер охраны).

Инструмент Geranium предназначен для специалистов с различной компетенцией от рабочей группы ArcNet до интересующихся пользователей. В ходе проекта ArcNet сформировалась определенная терминология, используемая учеными ArcNet для обсуждения деталей и выведенная в пользовательский интерфейс Geranium. Часть этой терминологии может быть заменена на обобщенные и более понятные термины, а часть расшифрована в виде словаря. 

Функциональность современной версии Geranium обеспечивает интерактивное взаимодействие с пользователем по формированию запросов через формы ввода и выдаче результатов в графическом и табличном виде. Для интересующихся пользователей необходима интерпретация, которая может быть реализована через динамически формируемый текстовый отчет (machine report, instant report), в котором лингвистические конструкции нанизаны на численные значения сводки, а также служат связующими элементами повествования.

Machine reports облегчают интерпретацию данных, но могут быть недостаточными для глубокого понимания интересующимися пользователями. Для их обучения в качестве связующего моста будет на основе 2-3 machine reports будут подготовлены соотнесенные с ними human reports.

Для ключевых, выделенных экспертами, районов пересечения ценных природоохранных районов и активной хозяйственной деятельности на основе machine report учеными ArcNet может быть сформирован human report для включения в брошюру, по материалам которой могут быть организованы совещания заинтересованных сторон.

На последующих этапах допускается корректировка оценок хозяйственной деятельности, а так как формирование отчетов Geranium происходит динамически, то изменения сразу учитываются. На последующих этапах принятые и утвержденные решения по оценке совместимости могут быть включены в функционал Geranium как в виде пространственных данных, так и в виде human reports.

TODO: human use

## Деятельность / методы /этапы


## Оценка

