---
pagetitle: industry template
---

## Aquaculture



### AC: Cages (salmon, cod etc) {#i0a4c17ef}

This type of aquaculture can be associated with the following impacts on marine environment: chemical pollution, genetic and organic pollution, spread of parasites and infections from cages into the wild populations. It affects not only wild populations but also benthic communities especially if located in semi-enclosed water areas. It also requires some coastal infrastructure and an increased level of shipping to maintain and transport the product.

Examples: salmon aquaculture in Norway, Faroe Islands and Russian Kola Peninsula
Marine mammals

Seabirds

Fishes

Benthos

Coastal features





### AM: Mussels, Oysters, scallops etc {#i78c71a23}

This type of aquaculture can be associated with organic pollution when the farms are densely concentrated within a limited space. It can also change the pH of the waters around it.  It also requires some coastal infrastructure and an increased level of shipping to maintain and transport the product.
Examples: The Bering Sea, Canada
Marine mammals

Seabirds

Fishes

Benthos

Coastal features





### AS: seaweed farming {#ia5e60724}

There are plans for seaweed farming in the White Sea. This type of aquaculture is associated with less impacts compared to the others but still leads to alteration of the seascape and increased ship traffic for maintenance and harvesting.
Marine mammals

Seabirds

Fishes

Benthos

Coastal features


