---
pagetitle: industry template
---

## Mining

Oil & gas production 

Offshore hydrocarbon production starts with engineering and geological surveys at the first stage and continues with well drilling, platforms installation at the next stage. Once the production is established the infrastructure requires maintenance and hydrocarbons need to be stored and transported. In case of LNG it also needs to be processed on site before transportation.
Each stage is associated with various impacts of different scale and intensity. We assessed the entire complex of the industry-associated impacts for each Conservation Feature as there is no reason to conduct surveys without planning to drill and to start oil production, and once it is produced it needs to be stored and transported and once infrastructure is there it requires access and maintenance. 

Marine mammals

Seabirds

Fishes

Benthos

Coastal features


### MOP: oil production {#i2c466286}

Engineering and geological surveys typically include: drilling of exploratory boreholes, sampling of various geological materials; geophysical surveys (continuous seismoacoustic profiling, side-scan sonar, etc.). These surveys are associated with the following impacts: noise pollution (from ships and from seismic surveys), petrochemical pollution (leaks from ships and equipment), light pollution from ships and drilling platforms, physical disturbance and destruction of benthic habitats as well as short-term changes in the water turbidity levels. 

Next stages of oil production are associated with high risk of oil and other petrochemicals pollution including catastrophic one, physical disturbance and destruction of habitats caused by installation of platforms and shipping, noise pollution both underwater and in the air (from helicopters), changes in the ice cover and light pollution.

Examples: Prirazlomnaya in the Pechora Sea, Norway, Alaska

Marine mammals

Seabirds

Fishes

Benthos

Coastal features



### MGP: gas production {#i3b90dd50}

Engineering and geological surveys typically include: drilling of exploratory boreholes, sampling of various geological materials; geophysical surveys (continuous seismoacoustic profiling, side-scan sonar, etc.). These surveys are associated with the following impacts: noise pollution (from ships and from seismic surveys), petrochemical pollution (leaks from ships and equipment), light pollution from ships and drilling platforms, physical disturbance and destruction of benthic habitats as well as short-term changes in the water turbidity levels.

Next stages of gas production are associated with the same risks and impacts as production of oil: petrochemicals pollution, physical disturbance and destruction of habitats caused by installation of platforms and shipping, noise pollution both underwater and in the air (from helicopters), changes in the ice cover and light pollution. The difference is that there is no risk of catastrophic oil spills but there are risks of LNG and other chemical leaks and also water warming in case it is used as a cooling agent in the process of production.

Examples: LNG projects in the Western Siberian Arctic

Marine mammals

Seabirds

Fishes

Benthos

Coastal features





### MOM: Other minerals production/mining {#i54e9684f}

Sand is already being mined from seafloor in some areas of the World Ocean. There are plans for deep seabed mining for ferromanganese nodules and rare-earth metals. Associated impacts from such off-shore mining will be similar to the ones described for off-shore gas production including engineering and geological surveys and associated ship work: noise pollution, petrochemical pollution (leaks from ships and equipment), light pollution, physical disturbance. 
 Additionally it will lead to significant impact on benthic habitats including their complete destruction, long-term changes in the water turbidity levels and local hydrological characteristics.  

Examples: ?

Marine mammals

Seabirds

Fishes

Benthos

Coastal features




### MCM: Coastal mining {#i4cfac06b}

On-shore mining directly impacts coastal and marine ecosystems through pollution by drains, leaks and discharges. Also coastal mining leads to development of coastal infrastructure (ports and terminals) destroying coastal habitats. Their construction will lead to an increase in ship and air traffic with all associated impacts similar to the impacts from off-shore mining - light and noise pollution, oil and other petrochemicals pollution, plastic pollution, habitat degradation etc.

Examples: LNG in Yamal, Russia, Nornikel, Russia, coal (?)

Marine mammals

Seabirds

Fishes

Benthos

Coastal features
