---
pagetitle: industry template
---

## Shipping

All ships have similar following impacts on marine environment: underwater noise pollution, physical disturbance, biological pollution (transportation of invasive species), risks of collisions with birds and mammals, waste pollution, light pollution, ice cover destruction (especially in the port areas where permanent ice-free channels are kept), shipping channels can also be a reason for dredging with all associated consequences. 
Apart from this the impacts from shipping to a large extent depend on the type of fuel a particular vessel uses and the type of cargo it carries. For example if a vessel carries oil or petrochemicals or uses HFO (Heavy Fuel Oil) as a fuel scale of impact and pollution can be much bigger than a pollution from a container ship running on LNG. Because of this we divided shipping into the 5 categories: tankers - ships carrying oil and petrochemicals and other cargo and passenger vessels using HFO, LFO, LNG or nuclear power as a source of power.
More about difference between different vessel fuel types and their impact on marine environment is here: https://www.hfofreearctic.org/en/front-page/ 

### ST: Tanker (oil and petrochemicals) {#if3312b50}

In case a ship carries oil and other petrochemicals it does not matter what fuel it uses for the purposes of the assessment - in case of emergency it can be a source of ecological disaster affecting all components of biodiversity.
Examples: tankers carrying oil from Varandey, the Pechora Sea across the Barents Sea, Alaska?
Briefly describe distribution of tanker shipping routes in the Arctic
Marine mammals

Seabirds

Fishes

Benthos

Coastal features



### SHF: Cargo/Container/Passenger - Heavy Fuel Oil {#i036007f2}

HFO or marine fuel oil is still the most common type of fuel for ships, it is being used in 75% percent of vessels in the Arctic. It is considered the dirtiest and cheapest type of fossil fuel, which is obtained from oil. HFO degrades very slowly in cold waters, and it is literally impossible to collect it in case of an oil spill. Also use of HFO causes big amounts of sulfur oxide and black soot emissions. It is already forbidden to use it in the Antarctic and it is going to be banned in the Arctic after 2029.
Marine mammals

Seabirds

Fishes

Benthos

Coastal features






### SLF: Cargo/Container/Passenger - Light Fuel Oil {#i6635f08f}

Light Fuel Oil or marine gasoil is a ship fuel with a lower amount of sulfur oxide, and accordingly ships with this fuel emit less pollutants. In the event of a spill, light fuel covers the surface with a film, evaporating and dissolving much faster than marine fuel oil.
Marine mammals

Seabirds

Fishes

Benthos

Coastal features





### SLN: Cargo/Container/Passenger - LNG-powered vessel {#i2e4dc7b4}

Liquified Natural Gas, LNG considered to be a relatively ecological alternative fuel. Its sulfur oxide level is 95% lower than in HFO and carbon dioxide emissions are 20-25% lower. In case of leakage gas is warming and evaporates and does not pollute marine environment.
Marine mammals

Seabirds

Fishes

Benthos

Coastal features




### SN: Nuclear-powered vessel {#i884a838b}

Nuclear-powered vessels do not emit any pollutants in the atmosphere and water during regular operation. In case of an accident a vessel can be a source of radioactive pollution of the marine environment. However during the decades of operation of such ships, there was no threat to the environment.
Marine mammals

Seabirds

Fishes

Benthos

Coastal features


